services:
  - type: web
    name: qr-order-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:10000 app:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"